"""Base tables that pre-date the first autogenerated migration.

The original initial migration (b78ae4fb756b) was autogenerated against a
database that already had these tables, so a fresh database could not be
built with ``alembic upgrade head``. This root revision creates them in the
shape later migrations expect (columns added by later revisions are omitted).
Existing databases are already past this revision and never run it.
"""
from alembic import op
import sqlalchemy as sa


revision = "a00000000000"
down_revision = None
branch_labels = None
depends_on = None


def _exists(table: str) -> bool:
    return sa.inspect(op.get_bind()).has_table(table)


def upgrade():
    if not _exists("users"):
        op.create_table(
            "users",
            sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
            sa.Column("email", sa.String(255), nullable=False),
            sa.Column("username", sa.String(100), nullable=False),
            sa.Column("full_name", sa.String(255)),
            sa.Column("hashed_password", sa.String(255), nullable=False),
            sa.Column("role", sa.String(20), nullable=False, server_default="client"),
            sa.Column("is_active", sa.Boolean(), server_default=sa.true()),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        )
        op.create_index("ix_users_email", "users", ["email"], unique=True)
        op.create_index("ix_users_username", "users", ["username"], unique=True)

    if not _exists("sentiment_options"):
        op.create_table(
            "sentiment_options",
            sa.Column("id", sa.SmallInteger(), primary_key=True, autoincrement=True),
            sa.Column("value", sa.String(20), nullable=False, unique=True),
            sa.Column("label", sa.String(50), nullable=False),
            sa.Column("color", sa.String(30)),
            sa.Column("sort_order", sa.SmallInteger(), server_default="0"),
        )
    if not _exists("priority_options"):
        op.create_table(
            "priority_options",
            sa.Column("id", sa.SmallInteger(), primary_key=True, autoincrement=True),
            sa.Column("value", sa.String(20), nullable=False, unique=True),
            sa.Column("label", sa.String(50), nullable=False),
            sa.Column("color", sa.String(30)),
            sa.Column("score", sa.SmallInteger()),
            sa.Column("sort_order", sa.SmallInteger(), server_default="0"),
        )
    if not _exists("category_options"):
        op.create_table(
            "category_options",
            sa.Column("id", sa.SmallInteger(), primary_key=True, autoincrement=True),
            sa.Column("value", sa.String(50), nullable=False, unique=True),
            sa.Column("label", sa.String(50), nullable=False),
            sa.Column("description", sa.Text()),
            sa.Column("sort_order", sa.SmallInteger(), server_default="0"),
        )

    if not _exists("email_integrations"):
        op.create_table(
            "email_integrations",
            sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
            sa.Column("provider", sa.String(20), nullable=False),
            sa.Column("email_address", sa.String(255), nullable=False, unique=True),
            sa.Column("access_token", sa.Text()),
            sa.Column("refresh_token", sa.Text()),
            sa.Column("token_expiry", sa.DateTime(timezone=True)),
            sa.Column("is_active", sa.Boolean(), server_default=sa.true()),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        )

    if not _exists("notifications"):
        # The FK to emails is added in k0e1f2a3b4c5 (emails is created by the next revision).
        op.create_table(
            "notifications",
            sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
            sa.Column("email_id", sa.Integer()),
            sa.Column("type", sa.String(50), nullable=False),
            sa.Column("title", sa.String(255), nullable=False),
            sa.Column("message", sa.Text()),
            sa.Column("is_read", sa.Boolean(), server_default=sa.false()),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        )

    if not _exists("allowed_domains"):
        op.create_table(
            "allowed_domains",
            sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
            sa.Column("domain", sa.String(255), nullable=False, unique=True),
            sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
            sa.Column("notes", sa.String(500)),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        )


def downgrade():
    for table in (
        "allowed_domains", "notifications", "email_integrations",
        "category_options", "priority_options", "sentiment_options", "users",
    ):
        op.drop_table(table)
