"""initial_schema

Revision ID: b78ae4fb756b
Revises: 
Create Date: 2026-06-04 14:01:45.473638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b78ae4fb756b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.String(length=512), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=True),
    sa.Column('body_plain', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('body_clean', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('thread_id', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['email_integrations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_table('email_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('primary_emotion', sa.String(length=50), nullable=True),
    sa.Column('emotions_json', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('category_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('priority_score', sa.SmallInteger(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('suggested_reply', sa.Text(), nullable=True),
    sa.Column('routed_to', sa.String(length=100), nullable=True),
    sa.Column('routing_reason', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_id')
    )
    op.create_table('email_replies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachments_json', sa.JSON(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'notifications', 'emails', ['email_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_table('email_replies')
    op.drop_table('email_analyses')
    op.drop_table('emails')
    # ### end Alembic commands ###
